workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.englishwithgames"
        TEAM_ID: $CM_TEAM_ID
    scripts:
      - name: Set up code signing settings
        script: |
          echo "Using automatic code signing with Team ID: $TEAM_ID"
          echo "Bundle ID: $BUNDLE_ID"
      - name: Get Flutter packages
        script: flutter pub get
             - name: Create export options plist
         script: |
           cat > /tmp/exportOptions.plist << EOF
           <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
           <plist version="1.0">
           <dict>
               <key>method</key>
               <string>app-store</string>
               <key>teamID</key>
               <string>$TEAM_ID</string>
               <key>signingStyle</key>
               <string>automatic</string>
               <key>uploadBitcode</key>
               <false/>
               <key>uploadSymbols</key>
               <true/>
               <key>compileBitcode</key>
               <false/>
           </dict>
           </plist>
           EOF
       - name: Flutter build ipa
         script: |
           flutter build ipa \
             --release \
             --export-options-plist=/tmp/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
         publishing:
       app_store_connect:
         api_key: $CM_APP_STORE_CONNECT_API_KEY
         key_id: $CM_APP_STORE_CONNECT_API_KEY_ID
         issuer_id: $CM_APP_STORE_CONNECT_ISSUER_ID
         submit_to_testflight: true
         submit_to_app_store: false

  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.englishwithgames"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter build apk
        script: flutter build apk --release
      - name: Flutter build app bundle
        script: flutter build appbundle --release
    artifacts:
      - build/*/outputs/*.apk
      - build/*/outputs/*/mapping.txt
      - flutter_drive.log
